language: node_js
sudo: true
node_js: 4
script:
- npm run build
- npm run lint
- npm codecov
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: WatsonPlatformServices
  space: appgallery
  on:
    repo: watson-developer-cloud/social-customer-care
    branch: master
  skip_cleanup: true
